services:
  ordersyncapi1:
    build:
      context: .
      dockerfile: OrderSyncApi/Dockerfile
    ports:
      - 8080
    depends_on:
      - redis

  ordersyncapi2:
    build:
      context: .
      dockerfile: OrderSyncApi/Dockerfile
    ports:
      - 8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    command: [ "redis-server", "--appendonly", "yes" ] 
    volumes:
      - redis_data:/data
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

  k6:
    image: grafana/k6:latest
    container_name: k6
    entrypoint: ["k6", "run", "/scripts/stress-test.js"]
    volumes:
      - ./K6:/scripts 
    depends_on:
      - ordersyncapi1
      - ordersyncapi2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - ordersyncapi1
      - ordersyncapi2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 

volumes:
  redis_data:
    driver: local
