services:
  ordersyncapi:
    build:
      context: .
      dockerfile: OrderSyncApi/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Porta padrão do Redis
    command: [ "redis-server", "--appendonly", "yes" ] # Configura Redis com persistência
    volumes:
      - redis_data:/data
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

  k6:
    image: grafana/k6:latest
    container_name: k6
    entrypoint: ["k6", "run", "/scripts/stress-test.js"]
    volumes:
      - ./K6:/scripts # Ajuste para refletir sua estrutura
    depends_on:
      - ordersyncapi

volumes:
  redis_data:
    driver: local
