name: .NET 8 Build, Docker Build

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Install Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore OrderSync.sln

      - name: Build
        run: dotnet build OrderSync.sln --no-restore --configuration Release
        
      - name: Run tests with coverage
        run: |
          dotnet test OrderSyncApi.Tests/OrderSyncApi.Tests.csproj --no-build --collect:"XPlat Code Coverage"
        continue-on-error: true
        
      - name: Convert coverage to XML
        run: |
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Cobertura

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"Leock9_SoulMenu" /o:"leock9" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml"
          dotnet build SoulMenu.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"


  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: needs.build.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and tag Docker image for API
        run: |
          docker build -f OrderSyncApi/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/ordersyncapi:v1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ordersyncapi:v1
